#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : numlockx
Version  : 1.2
Release  : 2
URL      : http://deb.debian.org/debian/pool/main/n/numlockx/numlockx_1.2.orig.tar.gz
Source0  : http://deb.debian.org/debian/pool/main/n/numlockx/numlockx_1.2.orig.tar.gz
Summary  : Turns on the numlock key in X11.
Group    : Development/Tools
License  : MIT
Requires: numlockx-bin = %{version}-%{release}
Requires: numlockx-license = %{version}-%{release}
BuildRequires : libXtst-dev
BuildRequires : pkgconfig(ice)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xext)

%description
NUMLOCKX 1.2

This little thingy allows you to start X with NumLock turned on ( which is
a feature that a lot of people seem to miss and nobody really knew how to
achieve this ).
This code relies on X extensions called XTest and XKB, so you need to have
at least one of these X extensions installed ( you most probably do ).
Please note that I'm not interested in problems caused by your distribution
being different from mine. NumLockX is written so it should work on plain X,
and I don't have the time to play with all distros there are, sorry.
If it doesn't work with your distro because they changed something
in the configuration files, bother them to include this package with their
next release ( with the necessary modifications ). It's much better that way,
since NumLockX requires modifications of several files and it's better if
they do the changes themselves. This is supposed to be the last version
of NumLockX anyway ( hopefully ).
The same way, please don't send me any binary packages. Such packages simply
can't be good because they need to modify files that don't belong to them.
Please bother your favourite distribution instead.
QUICK INSTALL :

%package bin
Summary: bin components for the numlockx package.
Group: Binaries
Requires: numlockx-license = %{version}-%{release}

%description bin
bin components for the numlockx package.


%package license
Summary: license components for the numlockx package.
Group: Default

%description license
license components for the numlockx package.


%prep
%setup -q -n numlockx-1.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568744561
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1568744561
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/numlockx
cp LICENSE %{buildroot}/usr/share/package-licenses/numlockx/LICENSE
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/numlockx

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/numlockx/LICENSE
